spring:
  output:
    ansi:
      enabled: ALWAYS

  datasource:
    hikari:
      jdbc-url: jdbc:h2:tcp://localhost/~/_dev/01.Private/04.Spring/Lab/bookshop/bookshop
      driver-class-name: org.h2.Driver
      username: sa
      password:

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging.level:
  org.hibernate.SQL: debug
#  org.hibernate.type: trace
